Get     http://localhost:3000/api/domicilio HTTP/1.1
Content-Type: application/json

{
  "IdDomicilio": 10,
  "IdPedido": 3,
  "IdDomiciliario": 1,
  "Observacion": "Entrega  para el Miercoles",
  "FechaEntrega": "2023-12-4",
  "DireccionDomicilio": "Calle Principal 123",
  "HoraEntrega": "12:00", 
  "EstadoDomicilio": "Pendiente"
}
###
POST     http://localhost:3000/api/domicilio/6563e0cafcc1dbe118842149 HTTP/1.1
###

PUT      http://localhost:3000/api/domicilio/6563e0cafcc1dbe118842149 HTTP/1.1

###
DELETE  http://localhost:3000/api/domicilio/6563e0cafcc1dbe118842149 HTTP/1.1




